# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1r99JxeipbmAxKN8Q3W4v8SkIqtnRXFKd
"""

import streamlit as st

st.write('Hello *World*! :sunglases:')